baseURL = 'https://seanbowers.tech/'
languageCode = 'en-us'
title = '~/seanbowers.tech'
theme = "archie"
copyright = "© Sean Bowers"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Still terminal after all these years"

# Social Tags

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/seanaaronbowers/"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:seanbowers@protonmail.com"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3

[[menu.main]]
name = "Links"
url = "/links"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
